### ISSUE TITLE
Wrong return type?

### ISSUE THREAD

**Issue by dje4321** [sphaerophoria/stream-os#1]
Watching the VOD, and noticed Either output has its return types swapped around

```
impl<R1, R2, F1, F2> Future for Select<F1, F2>
where
    F1: Future<Output = R1> + Unpin,
    F2: Future<Output = R2> + Unpin,
{
    type Output = Either<(R1, F2), (R2, F1)>;

    fn poll(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        let f1 = Pin::new(self.f1.as_mut().expect("Expected f1 to be valid"));
        if let Poll::Ready(ret) = f1.poll(cx) {
            let f2 = core::mem::take(&mut self.f2);
            return Poll::Ready(Either::Left((ret, f2.expect("Expected f2 to be valid"))));
        }

        let f2 = Pin::new(self.f2.as_mut().expect("Expected f2 to be valid"));
        if let Poll::Ready(ret) = f2.poll(cx) {
            let f1 = core::mem::take(&mut self.f1);
            return Poll::Ready(Either::Right((ret, f1.expect("Expected f1 to be valid"))));
        }

        Poll::Pending
    }
}
```

Future F1 is defined as having output type R1 with Future F2 having return type R2. However in your Either output statement, you define the left as being R1 with Future 2, or R2 with Future 1.

**Comment by sphaerophoria** [comment]
Ah I can see the confusion, however this is expected behavior!

There are some docs to scroll through on the original futures implementation here https://docs.rs/futures/latest/futures/future/fn.select.html. The idea is that I feed in 2 things, and I get back 2 things. The things I feed in are 2 futures, however only a single future will complete. So what do I get out? Well if future 1 completes, future 1 is no longer valid, it's finished. So F1 converts to R1, but F2 has not completed yet, so we return the future so that the user can continue to use it.

I'm having trouble coming up with a real world example for this that wouldn't be easier to do another way, but the concept I think is right.

**Comment by dje4321** [comment]
Thanks for the info. I get what your trying todo now. You have 3 possible states (Technically 4 if both futures finish _**exactly**_ at the same time however the code would default to the left case since it would presume the other future is still pending)

State 1: 
Future 1: Pending
Future 2: Pending

State 2:
Future 1: Ready
Future 2: Pending

State 3: 
Future 1: Pending
Future 2: Ready

So if any of the futures finish first, you return with the result of the finished future, and a handle to the future that has not yet finished so it can be consumed later.
